### ISSUE TITLE
JP3 should be named JP1

### ISSUE THREAD

**Issue by ghost** [sparkfun/9DOF_Sensor_Stick#4]

**Comment by ToniCorinne** [comment]
So, fiducials, the logo, standoffs are all JP prefixes. Because of this, JP3 is actually JP3. Do we need to update all of those other prefixes to something else if we are not to use JP# for those then?

**Comment by ghost** [comment]
I'd swap the names for the fiducial named JP1 and the header named JP3 since the names for the standoffs or fiducials don't appear by default and won't be present in the pdf version of the schematic. The rest of the names can stay the same. It'll make more sense/look cleaner with that header named JP1.

**Comment by mgrusin** [comment]
At some point can we change the default designation for fiducials etc. to
something other than JP? It causes a lot of dumb problems like this. Since
it doesn't show up it could be FIDx, LOGOx, MIKEx etc.

-Mike Grusin
SparkFun Electronics
303 284-0979 x 405
"This is only temporary... unless it works!" -Red Green

**Comment by ToniCorinne** [comment]
I personally agree with Mike, but I think that's a discussion better fit for the checklist repo perhaps? 

Anyway, change was fixed and pushed for this specific board.
