### ISSUE TITLE
Eng. Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/9DOF_Sensor_Stick#9]
1) The version number for the design in the "new_rev" repo is v20 while current storefront version is v16. This is an odd situation, this design has attributes of both and new product and a product rev, which makes assigning a version number to the design difficult. I just want to make sure that we increment this design's version numbers properly.

2) There are some seemingly necessary trace width variations throughout the design. Some of the signals around the IC change between 8mil and 10mil. The VDD trace changes from 15mil to 20mil  at C2 when a 20mil width could work for the entire trace.

3) Spec sheet specifies the use of the Sparkfun-2-layer-STANDARD.dru, the DRU being used in the design is Sparkfun-2-layer-TIGHT.dru. 

4) Per the spec. sheet, the goal of this design is to create a single IC 9dof that has a smaller footprint than our current LSM9DS1 Breakout in order to allow usage in applications that require a smaller device because of size and space constraints. Based on the goal of the product, I think that we should shrink this board down even more (smaller dimensions) with some tight trace work. This would add to the value and usability of the board, as well as validate the use of the tight dru.

**Comment by awende** [comment]
1) Bumping up to v20 was intentional. Given that the board is so different than v15, It should be bumped up to 2.0.

2) Any pin connected to the LSM9DS1 needs to be smaller than 10mil to avoid clearance issues. After closer inspection, the 15mil traces can be bumped back up to 20mil from VDD to C2.

3) It will need to be upgraded to Sparkfun-2-layer-TIGHT.dru.

4) Spec says to maintain at least the same board size as previous version. v15 is 0.4" x 1.35". The new design dropped the dimensions down to 0.4" x 1.0". However, in the updated design, I was able to shave off 100mil and bring the overall length to 0.9".

**Comment by ericorosel** [comment]
(1) Sounds good on v20, I assume the plan is to then go to v21 for reds?

(2) The trace connecting to the LSM between C5 and the C1 pin on the chip is 10 mil, not 8 mil

(3) Noted, thanks

(4) Awesome, I really think that even shaving off that 100 mil will add to the value of this board! Thanks Alex

**Comment by ericorosel** [comment]
(2) continued... One of the VDD traces entering the IC has a 9 mil width segment where the trace hits the IC pad

**Comment by awende** [comment]
Fixed trace widths issue.
